=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/amLogMessage.dtd
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2005 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: amLogMessage.dtd,v 1.4 2008/08/19 19:10:56 veiming Exp $

-->


<!-- This DTD defines the document structure for log messages.

Unique Declaration name for DOCTYPE tag: "OpenSSO Log
Message DTD"
-->

<!ELEMENT logmessages (
    (logmessage)+
) >
<!ATTLIST logmessages
    prefix	CDATA	    #REQUIRED
>

<!ELEMENT logmessage (
    (datainfo)+,
    (triggers)+,
    (actions)*
) >
<!ATTLIST logmessage
    name	CDATA	    #REQUIRED
    loglevel
	(LL_CONFIG|LL_FINER|LL_FINE|LL_FINEST|LL_INFO|LL_SEVERE|LL_ALL) "LL_INFO"
    id		CDATA	    #REQUIRED
    description	CDATA	    #IMPLIED
>

<!ELEMENT datainfo (
    (item)*
) >

<!ELEMENT triggers (
    (item)*
) >

<!ELEMENT actions (
    (item)*
) >

<!ELEMENT item (#PCDATA) >

=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/LoggingLogMessageIDs.xml
<!--
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: LoggingLogMessageIDs.xml,v 1.3 2008/08/19 19:10:54 veiming Exp $

    Copyright 2008 Sun Microsystems Inc. All Rights Reserved
-->

<!DOCTYPE logmessages
    PUBLIC "OpenSSO Log Message DTD/EN"
    "jar://com/sun/identity/log/messageid/amLogMessage.dtd"
>

<logmessages prefix="LOG">
    <logmessage name="LOG_START_NEW_LOGGER" id="1"
	loglevel="LL_INFO"
	description="Logging Started - New Logger">
	<datainfo>
	    <item>current location</item>
	</datainfo>
	<triggers>
	    <item>Logging started by getting a new Logger.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="LOG_END" id="2"
	loglevel="LL_INFO"
	description="Logging Terminated - Server Stopped">
	<datainfo>
	    <item>current location</item>
	</datainfo>
	<triggers>
	    <item>Logging terminated by server shutdown.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="LOG_START_CONFIG" id="3"
	loglevel="LL_INFO"
	description="Logging Started - Configuration Change">
	<datainfo>
	    <item>old location</item>
	    <item>new location</item>
	    <item>old backend</item>
	    <item>new backend</item>
	    <item>old security status</item>
	    <item>new security status</item>
	    <item>old status</item>
	    <item>new status</item>
	    <item>old level</item>
	    <item>new level</item>
	</datainfo>
	<triggers>
	    <item>Logging started after logging configuration change.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="LOG_END_CONFIG" id="4"
	loglevel="LL_INFO"
	description="Logging Terminated - Configuration Change">
	<datainfo>
	    <item>old location</item>
	    <item>new location</item>
	    <item>old backend</item>
	    <item>new backend</item>
	    <item>old security status</item>
	    <item>new security status</item>
	    <item>old status</item>
	    <item>new status</item>
	    <item>old level</item>
	    <item>new level</item>
	</datainfo>
	<triggers>
	    <item>Logging terminated by logging configuration change.</item>
	</triggers>
	<actions />
    </logmessage>
</logmessages>

=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/OAuth2ProviderLogMessageIDs.xml
<!DOCTYPE logmessages
        PUBLIC "OpenSSO Log Message DTD/EN"
        "jar://com/sun/identity/log/messageid/amLogMessage.dtd"
        >

<logmessages prefix="OAuth2Provider">
    <!-- Token operations -->
    <logmessage name="CREATED_TOKEN" id="1"
                loglevel="LL_INFO"
                description="Created an oauth 2.0 token">
        <datainfo>
            <item>message</item>
            <item>token info</item>
        </datainfo>
        <triggers>
            <item>Creating a new oauth 2.0 token</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="DELETED_TOKEN" id="2"
                loglevel="LL_INFO"
                description="Deleted an oauth 2.0 token">
        <datainfo>
            <item>message</item>
            <item>token info</item>
        </datainfo>
        <triggers>
            <item>Deleteing an oauth 2.0 token</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_CREATE_TOKEN" id="3"
                loglevel="LL_INFO"
                description="Failed to creating an oauth 2.0 token">
        <datainfo />
        <triggers>
            <item>Failed creating an oauth 2.0 token</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_DELETE_TOKEN" id="4"
                loglevel="LL_INFO"
                description="Failed deleting an oauth 2.0 token">
        <datainfo />
        <triggers>
            <item>Failed deleting an oauth 2.0 token</item>
        </triggers>
        <actions />
    </logmessage>

    <!-- Client Operations -->
    <logmessage name="CREATED_CLIENT" id="11"
                loglevel="LL_INFO"
                description="Created an oauth 2.0 Client">
        <datainfo>
            <item>message</item>
            <item>token info</item>
        </datainfo>
        <triggers>
            <item>Creating a new oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="DELETED_CLIENT" id="12"
                loglevel="LL_INFO"
                description="Deleted an oauth 2.0 client">
        <datainfo>
            <item>message</item>
            <item>token info</item>
        </datainfo>
        <triggers>
            <item>Deleteing an oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_CREATE_CLIENT" id="13"
                loglevel="LL_INFO"
                description="Failed to creating an oauth 2.0 client">
        <datainfo />
        <triggers>
            <item>Failed creating an oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_DELETE_CLIENT" id="14"
                loglevel="LL_INFO"
                description="Failed deleting an oauth 2.0 client">
        <datainfo />
        <triggers>
            <item>Failed deleting an oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="AUTHENTICATED_CLIENT" id="15"
                loglevel="LL_INFO"
                description="Authenticated an oauth 2.0 client">
        <datainfo>
            <item>message</item>
            <item>client id</item>
        </datainfo>
        <triggers>
            <item>Authenticating a oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_AUTHENTICATE_CLIENT" id="16"
                loglevel="LL_INFO"
                description="Failed authenticating an oauth 2.0 client">
        <datainfo />
        <triggers>
            <item>Failed authenticating an oauth 2.0 client</item>
        </triggers>
        <actions />
    </logmessage>
</logmessages>

=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/PolicyLogMessageIDs.xml
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2006 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: PolicyLogMessageIDs.xml,v 1.5 2008/08/19 19:10:54 veiming Exp $

-->

<!DOCTYPE logmessages
    PUBLIC "OpenSSO Log Message DTD/EN"
    "jar://com/sun/identity/log/messageid/amLogMessage.dtd"
>

<logmessages prefix="POLICY">
    <logmessage name="POLICY_EVALUATION" id="1"
	loglevel="LL_INFO"
	description="Evaluating policy succeeded">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	    <item>service type name</item>
	    <item>resource name</item>
	    <item>action names</item>
	    <item>policy decision</item>
	</datainfo>
	<triggers>
	    <item>Evaluating policy.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="PROTECTED_RESOURCES" id="2"
	loglevel="LL_INFO"
	description="Getting protected policy resources succeeded">
	<datainfo>
	    <item>principal name</item>
	    <item>resource name</item>
	    <item>protecting policies</item>
	</datainfo>
	<triggers>
	    <item>Getting protected policy resources.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="POLICY_CREATE_SUCCESS" id="3"
	loglevel="LL_INFO"
	description="Creating policy in a realm succeeded">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Creating policy in a realm.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="POLICY_MODIFY_SUCCESS" id="4"
	loglevel="LL_INFO"
	description="Modifying policy in a realm succeeded">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Modifying policy in a realm.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="POLICY_REMOVE_SUCCESS" id="5"
	loglevel="LL_INFO"
	description="Removing policy from a realm succeeded">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Removing policy from a realm.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="POLICY_ALREADY_EXISTS_IN_REALM" id="6"
	loglevel="LL_INFO"
	description="Policy already exists in the realm">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Creating policy in the realm.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_ADD_POLICY" id="7"
	loglevel="LL_INFO"
	description="Creating policy in a realm failed">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Creating policy in a realm.</item>
	</triggers>
	<actions>
            <item>Check if the user has privilege to create a policy in the realm.</item>
        </actions>
    </logmessage>
    <logmessage name="UNABLE_TO_REPLACE_POLICY" id="8"
	loglevel="LL_INFO"
	description="Replacing policy in a realm failed">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Replacing policy in a realm.</item>
	</triggers>
	<actions>
            <item>Check if the user has privilege to replace a policy in the realm.</item>
        </actions>
    </logmessage>
    <logmessage name="DID_NOT_REPLACE_POLICY" id="81"
	loglevel="LL_INFO"
	description="Did not replace policy - A diifferent policy with the new name already exists in the realm">
	<datainfo>
	    <item>new policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Replacing policy in a realm</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_REMOVE_POLICY" id="9"
	loglevel="LL_INFO"
	description="Removing policy from a realm failed">
	<datainfo>
	    <item>policy name</item>
	    <item>realm name</item>
	</datainfo>
	<triggers>
	    <item>Removing policy from a realm.</item>
	</triggers>
	<actions>
            <item>Check if the user has privilege to remove a policy from the realm.</item>
        </actions>
    </logmessage>
    <logmessage name="PROXIED_POLICY_EVALUATION" id="10"
	loglevel="LL_INFO"
	description="Computing policy decision by an administrator succeeded">
	<datainfo>
	    <item>admin name</item>
	    <item>principal name</item>
	    <item>resource name</item>
	    <item>policy decision</item>
	</datainfo>
	<triggers>
	    <item>Computing policy decision by an administrator.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="PROXIED_POLICY_EVALUATION_IGNORING_SUBJECTS" id="11"
	loglevel="LL_INFO"
	description="Computing policy decision by an administrator ignoring subjects succeeded">
	<datainfo>
	    <item>admin name</item>
	    <item>resource name</item>
	    <item>policy decision</item>
	</datainfo>
	<triggers>
	    <item>Computing policy decision by an administrator ignoring subjects.</item>
	</triggers>
	<actions />
    </logmessage>
</logmessages>

=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/EntitlementLogMessageIDs.xml
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: EntitlementLogMessageIDs.xml,v 1.1 2009/10/22 21:04:05 veiming Exp $

-->

<!DOCTYPE logmessages
    PUBLIC "OpenSSO Log Message DTD/EN"
    "jar://com/sun/identity/log/messageid/amLogMessage.dtd"
>

<logmessages prefix="ENTITLEMENT">

    <logmessage name="ATTEMPT_ADD_PRIVILEGE" id="1"
	loglevel="LL_INFO"
	description="Attempt to add privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Add privilege API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_ADD_PRIVILEGE" id="2"
	loglevel="LL_INFO"
	description="Privilege is added.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Add privilege API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_ADD_PRIVILEGE" id="3"
	loglevel="LL_INFO"
	description="Failed to add privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Add privilege API is called.</item>
	</triggers>
	<actions>
            <item>Privilege might already exists.</item>
            <item>Administrator might not have the permission to add privilege.</item>
	</actions>
    </logmessage>

    <logmessage name="ATTEMPT_ADD_REFERRAL" id="11"
	loglevel="LL_INFO"
	description="Attempt to add referral privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Add referral privilege API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_ADD_REFERRAL" id="12"
	loglevel="LL_INFO"
	description="Referral Privilege is added.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Add referral privilege API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_ADD_REFERRAL" id="13"
	loglevel="LL_INFO"
	description="Failed to add referral privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Add referral privilege API is called.</item>
	</triggers>
	<actions>
            <item>Privilege might already exists.</item>
            <item>Administrator might not have the permission to add referral privilege.</item>
	</actions>
    </logmessage>

    <logmessage name="ATTEMPT_REMOVE_PRIVILEGE" id="21"
	loglevel="LL_INFO"
	description="Attempt to remove privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Remove privilege API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_REMOVE_PRIVILEGE" id="22"
	loglevel="LL_INFO"
	description="Privilege is removed.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Removed privilege API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_REMOVE_PRIVILEGE" id="23"
	loglevel="LL_INFO"
	description="Failed to removed privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Removed privilege API is called.</item>
	</triggers>
	<actions>
            <item>Administrator might not have the permission to remove privilege.</item>
	</actions>
    </logmessage>

    <logmessage name="ATTEMPT_REMOVE_REFERRAL" id="31"
	loglevel="LL_INFO"
	description="Attempt to remove referral privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Remove referral privilege API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_REMOVE_REFERRAL" id="32"
	loglevel="LL_INFO"
	description="Referral privilege is removed.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	</datainfo>
	<triggers>
	    <item>Removed referral privilege API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_REMOVE_REFERRAL" id="33"
	loglevel="LL_INFO"
	description="Failed to removed referral privilege.">
	<datainfo>
	    <item>realm</item>
	    <item>privilege name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Removed referral privilege API is called.</item>
	</triggers>
	<actions>
            <item>Administrator might not have the permission to remove privilege.</item>
	</actions>
    </logmessage>

    <logmessage name="ATTEMPT_SAVE_APPLICATION" id="101"
	loglevel="LL_INFO"
	description="Attempt to save application.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	</datainfo>
	<triggers>
	    <item>Save application API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_SAVE_APPLICATION" id="102"
	loglevel="LL_INFO"
	description="Application is saved.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	</datainfo>
	<triggers>
	    <item>Save application API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_SAVE_APPLICATION" id="103"
	loglevel="LL_INFO"
	description="Failed to save application.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Save application API is called.</item>
	</triggers>
	<actions>
            <item>Administrator might not have the permission to save application.</item>
	</actions>
    </logmessage>

    <logmessage name="ATTEMPT_REMOVE_APPLICATION" id="111"
	loglevel="LL_INFO"
	description="Attempt to remove application.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	</datainfo>
	<triggers>
	    <item>Remove application API is called.</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="SUCCEEDED_REMOVE_APPLICATION" id="112"
	loglevel="LL_INFO"
	description="Application is removed.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	</datainfo>
	<triggers>
	    <item>Remove application API is called.</item>
	</triggers>
        <actions />
    </logmessage>
    <logmessage name="FAILED_REMOVE_APPLICATION" id="113"
	loglevel="LL_INFO"
	description="Failed to remove application.">
	<datainfo>
	    <item>realm</item>
	    <item>application name</item>
	    <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Remove application API is called.</item>
	</triggers>
	<actions>
            <item>Administrator might not have the permission to remove application.</item>
	</actions>
    </logmessage>
</logmessages>

=== robin-fei/openam-community-edition/openam-schema/openam-dtd-schema/src/main/resources/com/sun/identity/log/messageid/CoreTokenLogMessageIDs.xml
<!--
   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
  
    Copyright (c) 2009 Sun Microsystems Inc. All Rights Reserved
  
    The contents of this file are subject to the terms
    of the Common Development and Distribution License
    (the License). You may not use this file except in
    compliance with the License.

    You can obtain a copy of the License at
    https://opensso.dev.java.net/public/CDDLv1.0.html or
    opensso/legal/CDDLv1.0.txt
    See the License for the specific language governing
    permission and limitations under the License.

    When distributing Covered Code, include this CDDL
    Header Notice in each file and include the License file
    at opensso/legal/CDDLv1.0.txt.
    If applicable, add the following below the CDDL Header,
    with the fields enclosed by brackets [] replaced by
    your own identifying information:
    "Portions Copyrighted [year] [name of copyright owner]"

    $Id: CoreTokenLogMessageIDs.xml,v 1.1 2009/11/19 00:10:37 qcheng Exp $

-->

<!DOCTYPE logmessages
    PUBLIC "OpenSSO Log Message DTD/EN"
    "jar://com/sun/identity/log/messageid/amLogMessage.dtd"
>

<logmessages prefix="CORETOKEN">
    <logmessage name="TOKEN_CREATE_SUCCESS" id="1"
	loglevel="LL_INFO"
	description="Creating a token succeeded">
	<datainfo>
	    <item>token type</item>
	    <item>token subject</item>
	    <item>token attribute names</item>
	</datainfo>
	<triggers>
	    <item>Create token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="TOKEN_READ_SUCCESS" id="2"
        loglevel="LL_INFO"
        description="Retrieving a token succeeded">
	<datainfo>
	    <item>token type</item>
	    <item>token subject</item>
	</datainfo>
        <triggers>
            <item>Read token</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="TOKEN_UPDATE_SUCCESS" id="3"
        loglevel="LL_INFO"
        description="Updating a token succeeded">
        <datainfo>
	    <item>names of attributes updated</item>
        </datainfo>
        <triggers>
            <item>Update token</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="TOKEN_SEARCH_SUCCESS" id="4"
	loglevel="LL_INFO"
	description="Searching tokens succeeded">
	<datainfo>
	    <item>query</item>
	    <item>number of entries returned</item>
	</datainfo>
	<triggers>
	    <item>Search token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="TOKEN_DELETE_SUCCESS" id="5"
	loglevel="LL_INFO"
	description="Removing a token succeeded">
	<datainfo />
	<triggers>
	    <item>Delete token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="EXPIRED_TOKEN_DELETE_SUCCESS" id="6"
        loglevel="LL_INFO"
        description="Removing an expired token succeeded">
        <datainfo />
        <triggers>
            <item>Token expired</item>
        </triggers>
        <actions />
    </logmessage>
    <logmessage name="UNABLE_TO_CREATE_TOKEN" id="7"
	loglevel="LL_INFO"
	description="Creating a token failed">
	<datainfo>
            <item>error message</item>
            <item>token type</item>
            <item>token subject</item>
	    <item>token attribute names</item>
	</datainfo>
	<triggers>
	    <item>Create token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_READ_TOKEN" id="8"
	loglevel="LL_INFO"
	description="Retrieving a token failed">
	<datainfo>
            <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Read token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_UPDATE_TOKEN" id="9"
	loglevel="LL_INFO"
	description="Updating a token failed">
	<datainfo>
            <item>error message</item>
	</datainfo>
	<triggers>
	    <item>Update token</item>
	</triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_SEARCH_TOKEN" id="10"
        loglevel="LL_INFO"
        description="Searching tokens failed">
        <datainfo>
	    <item>query</item>
            <item>error message</item>
        </datainfo>
        <triggers>
            <item>Search Token</item>
        </triggers>
	<actions />
    </logmessage>
    <logmessage name="UNABLE_TO_DELETE_TOKEN" id="11"
        loglevel="LL_INFO"
        description="Removing a token failed">
        <datainfo>
            <item>error message</item>
        </datainfo>
        <triggers>
            <item>Delete token</item>
        </triggers>
	<actions />
    </logmessage>
</logmessages>
